# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='小寨', max_length=64),
            preserve_default=False,
        ),
    ]
